// Generated by gen_fir_data.py
#ifndef FIR_COEFFS_H
#define FIR_COEFFS_H

#include "ap_int.h"

#define N 32
const ap_int<16> coeffs[N] = {2, 2, 2, 1, -2, -6, -13, -17, -17, -8, 11, 42, 80, 118, 150, 168, 168, 150, 118, 80, 42, 11, -8, -17, -17, -13, -6, -2, 1, 2, 2, 2};

#endif  // FIR_COEFFS_H
