#!/usr/bin/env python3
"""
Generate FIR filter test data and coefficient header.

Output files written to the current working directory:
  - input.dat       : integer input samples
  - out.gold.dat    : golden FIR outputs
  - fir_coeffs.h    : C header containing scaled coefficients
"""

import os

import numpy as np
from scipy.signal import firwin, lfilter


def main():
    # Configuration -------------------------------------------------
    SAMPLES = 600
    SAMPLE_RATE = 48000
    CUTOFF_HZ = 4000
    TAPS = 32
    SCALE = 1024  # matches >>10 normalization in fir.cpp
    AMPLITUDE = 40000
    np.random.seed(0)

    # Generate input signal
    t = np.arange(SAMPLES) / SAMPLE_RATE
    sig = (
        0.5 * np.sin(2 * np.pi * 1000 * t)
        + 0.3 * np.sin(2 * np.pi * 7000 * t)
        + 0.05 * np.random.randn(SAMPLES)
    )
    sig_int = np.int32(np.round(sig * AMPLITUDE))

    #  FIR coefficients
    coeffs_f = firwin(TAPS, cutoff=CUTOFF_HZ, fs=SAMPLE_RATE)
    coeffs_i = np.int32(np.round(coeffs_f * SCALE))

    # Generate golden output
    acc = np.zeros(SAMPLES, dtype=np.int64)
    for n in range(SAMPLES):
        s = 0
        for k in range(TAPS):
            if n - k >= 0:
                s += int(sig_int[n - k]) * int(coeffs_i[k])
        acc[n] = s >> 10
    y_int = np.int32(acc)

    # Write files
    cwd = os.getcwd()
    input_path = os.path.join(cwd, "input.dat")
    golden_path = os.path.join(cwd, "out.gold.dat")
    coeff_path = os.path.join(cwd, "fir_coeffs.h")

    np.savetxt(input_path, sig_int, fmt="%d")
    np.savetxt(golden_path, y_int, fmt="%d")

    # write header with coefficients
    coeff_line = ", ".join(str(c) for c in coeffs_i)
    header_guard = "FIR_COEFFS_H"
    coeff_path = os.path.join(cwd, "fir_coeffs.h")
    with open(coeff_path, "w") as f:
        f.write("// Generated by gen_fir_data.py\n")
        f.write(f"#ifndef {header_guard}\n")
        f.write(f"#define {header_guard}\n\n")
        f.write('#include "ap_int.h"\n\n')
        f.write(f"#define N {TAPS}\n")
        f.write(f"const ap_int<16> coeffs[N] = {{{coeff_line}}};\n\n")
        f.write(f"#endif  // {header_guard}\n")

    # Console summary
    print("Generated:")
    print(f"  -> {os.path.basename(input_path)}  ({SAMPLES} samples)")
    print(f"  -> {os.path.basename(golden_path)} ({SAMPLES} golden outputs)")
    print(f"  -> {os.path.basename(coeff_path)}  ({TAPS} coefficients)")
    print("Include this header in fir.cpp as:")
    print('    #include "fir_coeffs.h"')


if __name__ == "__main__":
    main()
